import 'package:islami/ui/screens/main/tabs/quran/sura_dm.dart';
List<SuraDm> surasList = [
  SuraDm(
    suraIndex: 1,
    suraNameEn: "Al-Fatiha",
    suraNameAr: "الفاتحه",
    suraVerses: "7",
  ),
  SuraDm(
    suraIndex: 2,
    suraNameEn: "Al-Baqarah",
    suraNameAr: "البقرة",
    suraVerses: "286",
  ),
  SuraDm(
    suraIndex: 3,
    suraNameEn: "Aal-E-Imran",
    suraNameAr: "آل عمران",
    suraVerses: "200",
  ),
  SuraDm(
    suraIndex: 4,
    suraNameEn: "An-Nisa'",
    suraNameAr: "النساء",
    suraVerses: "176",
  ),
  SuraDm(
    suraIndex: 5,
    suraNameEn: "Al-Ma'idah",
    suraNameAr: "المائدة",
    suraVerses: "120",
  ),
  SuraDm(
    suraIndex: 6,
    suraNameEn: "Al-An'am",
    suraNameAr: "الأنعام",
    suraVerses: "165",
  ),
  SuraDm(
    suraIndex: 7,
    suraNameEn: "Al-A'raf",
    suraNameAr: "الأعراف",
    suraVerses: "206",
  ),
  SuraDm(
    suraIndex: 8,
    suraNameEn: "Al-Anfal",
    suraNameAr: "الأنفال",
    suraVerses: "75",
  ),
  SuraDm(
    suraIndex: 9,
    suraNameEn: "At-Tawbah",
    suraNameAr: "التوبة",
    suraVerses: "129",
  ),
  SuraDm(
    suraIndex: 10,
    suraNameEn: "Yunus",
    suraNameAr: "يونس",
    suraVerses: "109",
  ),
  SuraDm(
    suraIndex: 11,
    suraNameEn: "Hud",
    suraNameAr: "هود",
    suraVerses: "123",
  ),
  SuraDm(
    suraIndex: 12,
    suraNameEn: "Yusuf",
    suraNameAr: "يوسف",
    suraVerses: "111",
  ),
  SuraDm(
    suraIndex: 13,
    suraNameEn: "Ar-Ra'd",
    suraNameAr: "الرعد",
    suraVerses: "43",
  ),
  SuraDm(
    suraIndex: 14,
    suraNameEn: "Ibrahim",
    suraNameAr: "إبراهيم",
    suraVerses: "52",
  ),
  SuraDm(
    suraIndex: 15,
    suraNameEn: "Al-Hijr",
    suraNameAr: "الحجر",
    suraVerses: "99",
  ),
  SuraDm(
    suraIndex: 16,
    suraNameEn: "An-Nahl",
    suraNameAr: "النحل",
    suraVerses: "128",
  ),
  SuraDm(
    suraIndex: 17,
    suraNameEn: "Al-Isra",
    suraNameAr: "الإسراء",
    suraVerses: "111",
  ),
  SuraDm(
    suraIndex: 18,
    suraNameEn: "Al-Kahf",
    suraNameAr: "الكهف",
    suraVerses: "110",
  ),
  SuraDm(
    suraIndex: 19,
    suraNameEn: "Maryam",
    suraNameAr: "مريم",
    suraVerses: "98",
  ),
  SuraDm(
    suraIndex: 20,
    suraNameEn: "Ta-Ha",
    suraNameAr: "طه",
    suraVerses: "135",
  ),
  SuraDm(
    suraIndex: 21,
    suraNameEn: "Al-Anbiya",
    suraNameAr: "الأنبياء",
    suraVerses: "112",
  ),
  SuraDm(
    suraIndex: 22,
    suraNameEn: "Al-Hajj",
    suraNameAr: "الحج",
    suraVerses: "78",
  ),
  SuraDm(
    suraIndex: 23,
    suraNameEn: "Al-Mu'minun",
    suraNameAr: "المؤمنون",
    suraVerses: "118",
  ),
  SuraDm(
    suraIndex: 24,
    suraNameEn: "An-Nur",
    suraNameAr: "النّور",
    suraVerses: "64",
  ),
  SuraDm(
    suraIndex: 25,
    suraNameEn: "Al-Furqan",
    suraNameAr: "الفرقان",
    suraVerses: "77",
  ),
  SuraDm(
    suraIndex: 26,
    suraNameEn: "Ash-Shu'ara",
    suraNameAr: "الشعراء",
    suraVerses: "227",
  ),
  SuraDm(
    suraIndex: 27,
    suraNameEn: "An-Naml",
    suraNameAr: "النّمل",
    suraVerses: "93",
  ),
  SuraDm(
    suraIndex: 28,
    suraNameEn: "Al-Qasas",
    suraNameAr: "القصص",
    suraVerses: "88",
  ),
  SuraDm(
    suraIndex: 29,
    suraNameEn: "Al-Ankabut",
    suraNameAr: "العنكبوت",
    suraVerses: "69",
  ),
  SuraDm(
    suraIndex: 30,
    suraNameEn: "Ar-Rum",
    suraNameAr: "الرّوم",
    suraVerses: "60",
  ),
  SuraDm(
    suraIndex: 31,
    suraNameEn: "Luqman",
    suraNameAr: "لقمان",
    suraVerses: "34",
  ),
  SuraDm(
    suraIndex: 32,
    suraNameEn: "As-Sajda",
    suraNameAr: "السجدة",
    suraVerses: "30",
  ),
  SuraDm(
    suraIndex: 33,
    suraNameEn: "Al-Ahzab",
    suraNameAr: "الأحزاب",
    suraVerses: "73",
  ),
  SuraDm(
    suraIndex: 34,
    suraNameEn: "Saba",
    suraNameAr: "سبأ",
    suraVerses: "54",
  ),
  SuraDm(
    suraIndex: 35,
    suraNameEn: "Fatir",
    suraNameAr: "فاطر",
    suraVerses: "45",
  ),
  SuraDm(
    suraIndex: 36,
    suraNameEn: "Ya-Sin",
    suraNameAr: "يس",
    suraVerses: "83",
  ),
  SuraDm(
    suraIndex: 37,
    suraNameEn: "As-Saffat",
    suraNameAr: "الصافات",
    suraVerses: "182",
  ),
  SuraDm(suraIndex: 38, suraNameEn: "Sad", suraNameAr: "ص", suraVerses: "88"),
  SuraDm(
    suraIndex: 39,
    suraNameEn: "Az-Zumar",
    suraNameAr: "الزمر",
    suraVerses: "75",
  ),
  SuraDm(
    suraIndex: 40,
    suraNameEn: "Ghafir",
    suraNameAr: "غافر",
    suraVerses: "85",
  ),
  SuraDm(
    suraIndex: 41,
    suraNameEn: "Fussilat",
    suraNameAr: "فصّلت",
    suraVerses: "54",
  ),
  SuraDm(
    suraIndex: 42,
    suraNameEn: "Ash-Shura",
    suraNameAr: "الشورى",
    suraVerses: "53",
  ),
  SuraDm(
    suraIndex: 43,
    suraNameEn: "Az-Zukhruf",
    suraNameAr: "الزخرف",
    suraVerses: "89",
  ),
  SuraDm(
    suraIndex: 44,
    suraNameEn: "Ad-Dukhan",
    suraNameAr: "الدّخان",
    suraVerses: "59",
  ),
  SuraDm(
    suraIndex: 45,
    suraNameEn: "Al-Jathiya",
    suraNameAr: "الجاثية",
    suraVerses: "37",
  ),
  SuraDm(
    suraIndex: 46,
    suraNameEn: "Al-Ahqaf",
    suraNameAr: "الأحقاف",
    suraVerses: "35",
  ),
  SuraDm(
    suraIndex: 47,
    suraNameEn: "Muhammad",
    suraNameAr: "محمد",
    suraVerses: "38",
  ),
  SuraDm(
    suraIndex: 48,
    suraNameEn: "Al-Fath",
    suraNameAr: "الفتح",
    suraVerses: "29",
  ),
  SuraDm(
    suraIndex: 49,
    suraNameEn: "Al-Hujurat",
    suraNameAr: "الحجرات",
    suraVerses: "18",
  ),
  SuraDm(suraIndex: 50, suraNameEn: "Qaf", suraNameAr: "ق", suraVerses: "45"),
  SuraDm(
    suraIndex: 51,
    suraNameEn: "Adh-Dhariyat",
    suraNameAr: "الذاريات",
    suraVerses: "60",
  ),
  SuraDm(
    suraIndex: 52,
    suraNameEn: "At-Tur",
    suraNameAr: "الطور",
    suraVerses: "49",
  ),
  SuraDm(
    suraIndex: 53,
    suraNameEn: "An-Najm",
    suraNameAr: "النجم",
    suraVerses: "62",
  ),
  SuraDm(
    suraIndex: 54,
    suraNameEn: "Al-Qamar",
    suraNameAr: "القمر",
    suraVerses: "55",
  ),
  SuraDm(
    suraIndex: 55,
    suraNameEn: "Ar-Rahman",
    suraNameAr: "الرحمن",
    suraVerses: "78",
  ),
  SuraDm(
    suraIndex: 56,
    suraNameEn: "Al-Waqi'a",
    suraNameAr: "الواقعة",
    suraVerses: "96",
  ),
  SuraDm(
    suraIndex: 57,
    suraNameEn: "Al-Hadid",
    suraNameAr: "الحديد",
    suraVerses: "29",
  ),
  SuraDm(
    suraIndex: 58,
    suraNameEn: "Al-Mujadila",
    suraNameAr: "المجادلة",
    suraVerses: "22",
  ),
  SuraDm(
    suraIndex: 59,
    suraNameEn: "Al-Hashr",
    suraNameAr: "الحشر",
    suraVerses: "24",
  ),
  SuraDm(
    suraIndex: 60,
    suraNameEn: "Al-Mumtahina",
    suraNameAr: "الممتحنة",
    suraVerses: "13",
  ),
  SuraDm(
    suraIndex: 61,
    suraNameEn: "As-Saff",
    suraNameAr: "الصف",
    suraVerses: "14",
  ),
  SuraDm(
    suraIndex: 62,
    suraNameEn: "Al-Jumu'a",
    suraNameAr: "الجمعة",
    suraVerses: "11",
  ),
  SuraDm(
    suraIndex: 63,
    suraNameEn: "Al-Munafiqun",
    suraNameAr: "المنافقون",
    suraVerses: "11",
  ),
  SuraDm(
    suraIndex: 64,
    suraNameEn: "At-Taghabun",
    suraNameAr: "التغابن",
    suraVerses: "18",
  ),
  SuraDm(
    suraIndex: 65,
    suraNameEn: "At-Talaq",
    suraNameAr: "الطلاق",
    suraVerses: "12",
  ),
  SuraDm(
    suraIndex: 66,
    suraNameEn: "At-Tahrim",
    suraNameAr: "التحريم",
    suraVerses: "12",
  ),
  SuraDm(
    suraIndex: 67,
    suraNameEn: "Al-Mulk",
    suraNameAr: "الملك",
    suraVerses: "30",
  ),
  SuraDm(
    suraIndex: 68,
    suraNameEn: "Al-Qalam",
    suraNameAr: "القلم",
    suraVerses: "52",
  ),
  SuraDm(
    suraIndex: 69,
    suraNameEn: "Al-Haqqah",
    suraNameAr: "الحاقة",
    suraVerses: "52",
  ),
  SuraDm(
    suraIndex: 70,
    suraNameEn: "Al-Ma'arij",
    suraNameAr: "المعارج",
    suraVerses: "44",
  ),
  SuraDm(suraIndex: 71, suraNameEn: "Nuh", suraNameAr: "نوح", suraVerses: "28"),
  SuraDm(
    suraIndex: 72,
    suraNameEn: "Al-Jinn",
    suraNameAr: "الجن",
    suraVerses: "28",
  ),
  SuraDm(
    suraIndex: 73,
    suraNameEn: "Al-Muzzammil",
    suraNameAr: "المزّمّل",
    suraVerses: "20",
  ),
  SuraDm(
    suraIndex: 74,
    suraNameEn: "Al-Muddathir",
    suraNameAr: "المدّثر",
    suraVerses: "56",
  ),
  SuraDm(
    suraIndex: 75,
    suraNameEn: "Al-Qiyamah",
    suraNameAr: "القيامة",
    suraVerses: "40",
  ),
  SuraDm(
    suraIndex: 76,
    suraNameEn: "Al-Insan",
    suraNameAr: "الإنسان",
    suraVerses: "31",
  ),
  SuraDm(
    suraIndex: 77,
    suraNameEn: "Al-Mursalat",
    suraNameAr: "المرسلات",
    suraVerses: "50",
  ),
  SuraDm(
    suraIndex: 78,
    suraNameEn: "An-Naba'",
    suraNameAr: "النبأ",
    suraVerses: "40",
  ),
  SuraDm(
    suraIndex: 79,
    suraNameEn: "An-Nazi'at",
    suraNameAr: "النازعات",
    suraVerses: "46",
  ),
  SuraDm(
    suraIndex: 80,
    suraNameEn: "Abasa",
    suraNameAr: "عبس",
    suraVerses: "42",
  ),
  SuraDm(
    suraIndex: 81,
    suraNameEn: "At-Takwir",
    suraNameAr: "التكوير",
    suraVerses: "29",
  ),
  SuraDm(
    suraIndex: 82,
    suraNameEn: "Al-Infitar",
    suraNameAr: "الإنفطار",
    suraVerses: "19",
  ),
  SuraDm(
    suraIndex: 83,
    suraNameEn: "Al-Mutaffifin",
    suraNameAr: "المطفّفين",
    suraVerses: "36",
  ),
  SuraDm(
    suraIndex: 84,
    suraNameEn: "Al-Inshiqaq",
    suraNameAr: "الإنشقاق",
    suraVerses: "25",
  ),
  SuraDm(
    suraIndex: 85,
    suraNameEn: "Al-Buruj",
    suraNameAr: "البروج",
    suraVerses: "22",
  ),
  SuraDm(
    suraIndex: 86,
    suraNameEn: "At-Tariq",
    suraNameAr: "الطارق",
    suraVerses: "17",
  ),
  SuraDm(
    suraIndex: 87,
    suraNameEn: "Al-A'la",
    suraNameAr: "الأعلى",
    suraVerses: "19",
  ),
  SuraDm(
    suraIndex: 88,
    suraNameEn: "Al-Ghashiyah",
    suraNameAr: "الغاشية",
    suraVerses: "26",
  ),
  SuraDm(
    suraIndex: 89,
    suraNameEn: "Al-Fajr",
    suraNameAr: "الفجر",
    suraVerses: "30",
  ),
  SuraDm(
    suraIndex: 90,
    suraNameEn: "Al-Balad",
    suraNameAr: "البلد",
    suraVerses: "20",
  ),
  SuraDm(
    suraIndex: 91,
    suraNameEn: "Ash-Shams",
    suraNameAr: "الشمس",
    suraVerses: "15",
  ),
  SuraDm(
    suraIndex: 92,
    suraNameEn: "Al-Lail",
    suraNameAr: "الليل",
    suraVerses: "21",
  ),
  SuraDm(
    suraIndex: 93,
    suraNameEn: "Ad-Duha",
    suraNameAr: "الضحى",
    suraVerses: "11",
  ),
  SuraDm(
    suraIndex: 94,
    suraNameEn: "Ash-Sharh",
    suraNameAr: "الشرح",
    suraVerses: "8",
  ),
  SuraDm(
    suraIndex: 95,
    suraNameEn: "At-Tin",
    suraNameAr: "التين",
    suraVerses: "8",
  ),
  SuraDm(
    suraIndex: 96,
    suraNameEn: "Al-Alaq",
    suraNameAr: "العلق",
    suraVerses: "19",
  ),
  SuraDm(
    suraIndex: 97,
    suraNameEn: "Al-Qadr",
    suraNameAr: "القدر",
    suraVerses: "5",
  ),
  SuraDm(
    suraIndex: 98,
    suraNameEn: "Al-Bayyina",
    suraNameAr: "البينة",
    suraVerses: "8",
  ),
  SuraDm(
    suraIndex: 99,
    suraNameEn: "Az-Zalzalah",
    suraNameAr: "الزلزلة",
    suraVerses: "8",
  ),
  SuraDm(
    suraIndex: 100,
    suraNameEn: "Al-Adiyat",
    suraNameAr: "العاديات",
    suraVerses: "11",
  ),
  SuraDm(
    suraIndex: 101,
    suraNameEn: "Al-Qari'a",
    suraNameAr: "القارعة",
    suraVerses: "11",
  ),
  SuraDm(
    suraIndex: 102,
    suraNameEn: "At-Takathur",
    suraNameAr: "التكاثر",
    suraVerses: "8",
  ),
  SuraDm(
    suraIndex: 103,
    suraNameEn: "Al-Asr",
    suraNameAr: "العصر",
    suraVerses: "3",
  ),
  SuraDm(
    suraIndex: 104,
    suraNameEn: "Al-Humazah",
    suraNameAr: "الهمزة",
    suraVerses: "9",
  ),
  SuraDm(
    suraIndex: 105,
    suraNameEn: "Al-Fil",
    suraNameAr: "الفيل",
    suraVerses: "5",
  ),
  SuraDm(
    suraIndex: 106,
    suraNameEn: "Quraysh",
    suraNameAr: "قريش",
    suraVerses: "4",
  ),
  SuraDm(
    suraIndex: 107,
    suraNameEn: "Al-Ma'un",
    suraNameAr: "الماعون",
    suraVerses: "7",
  ),
  SuraDm(
    suraIndex: 108,
    suraNameEn: "Al-Kawthar",
    suraNameAr: "الكوثر",
    suraVerses: "3",
  ),
  SuraDm(
    suraIndex: 109,
    suraNameEn: "Al-Kafirun",
    suraNameAr: "الكافرون",
    suraVerses: "6",
  ),
  SuraDm(
    suraIndex: 110,
    suraNameEn: "An-Nasr",
    suraNameAr: "النصر",
    suraVerses: "3",
  ),
  SuraDm(
    suraIndex: 111,
    suraNameEn: "Al-Masad",
    suraNameAr: "المسد",
    suraVerses: "5",
  ),
  SuraDm(
    suraIndex: 112,
    suraNameEn: "Al-Ikhlas",
    suraNameAr: "الإخلاص",
    suraVerses: "4",
  ),
  SuraDm(
    suraIndex: 113,
    suraNameEn: "Al-Falaq",
    suraNameAr: "الفلق",
    suraVerses: "5",
  ),
  SuraDm(
    suraIndex: 114,
    suraNameEn: "An-Nas",
    suraNameAr: "الناس",
    suraVerses: "6",
  ),
];
abstract final class AppConstants {
  static const  String displayOnboarding = 'onboarding_seen';
}
